[programs.localnet]
sharing = "Hua5xPD28e5ovftEuzmxRwonzYvsNahGyxX8fJs5f1KD"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/helenamerk/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
