[programs.localnet]
sharing = "sharYRHd1q5fGpwNecudQrgQT9dT9U22U8Fi2K7VC6y"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/ubuntu/.config/solana/id.json"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.mocha.json -t 1000000 js/test/*.test.ts"
